# DATASET CONFIGURATION
dataset: mimic                          # MIMIC dataset
data_path: ../original_data/            # Path to dataset
n_classes: 19                           # Number of classes (paper mentions 19, p.10)
max_num: 20000                          # Maximum samples per class to use
problem_type: multi_label               # Multi-label classification problem for MIMIC

# Class descriptions for MIMIC (ICD-9 categories)
target_00: tuberculosis, found, unspecified, bacilli, bacteriological, examination, tubercle, histological, specified, sputum, microscopy, confirmed, infection, tuberculous, due
target_01: neoplasm, malignant, unspecified, lymph, nodes, benign, sites, cell, limb, site, lymphoma, hodgkin, skin, leukemia, specified
target_02: unspecified, type, diabetes, uncontrolled, disorders, deficiency, manifestations, stated, metabolism, specified, mention, mellitus, secondary, ii, juvenile
target_03: anemia, unspecified, disease, deficiency, cell, blood, specified, anemias, thalassemia, hemolytic, sickle, crisis, congenital, neutropenia, iron
target_04: disorder, unspecified, type, episode, remission, dependence, schizophrenia, drug, abuse, specified, bipolar, disorders, acute, current, chronic
target_05: migraine, without, unspecified, intractable, mention, status, migrainosus, elsewhere, classified, epilepsy, sleep, diseases, cerebral, stated, disorder
target_06: unspecified, eye, vision, impairment, disorders, retinal, corneal, glaucoma, acute, associated, loss, ear, cataract, chronic, total
target_07: unspecified, disease, heart, chronic, acute, infarction, artery, embolism, kidney, thrombosis, stage, failure, cerebrovascular, venous, without
target_08: due, acute, pneumonia, unspecified, chronic, respiratory, influenza, pulmonary, lung, virus, asthma, sinusitis, obstruction, bronchitis, diseases
target_09: unspecified, obstruction, without, mention, hemorrhage, ulcer, chronic, acute, perforation, hernia, specified, gangrene, recurrent, intestine, cholecystitis
target_10: unspecified, specified, chronic, lesion, female, kidney, acute, glomerulonephritis, genital, disorders, urinary, prostate, cervix, classified, elsewhere
target_11: condition, complication, unspecified, antepartum, mention, delivered, without, care, episode, applicable, postpartum, pregnancy, mother, abortion, labor
target_12: due, unspecified, dermatitis, ulcer, specified, abscess, pressure, cellulitis, skin, contact, erythematous, condition, body, carbuncle, furuncle
target_13: unspecified, region, arthropathy, joint, sites, specified, associated, site, foot, hand, ankle, shoulder, upper, forearm, pelvic
target_14: congenital, anomalies, unspecified, specified, anomaly, cleft, complete, deficiency, incomplete, longitudinal, without, limb, system, syndrome, partial
target_15: newborn, fetus, grams, fetal, affecting, unspecified, dates, light, malnutrition, without, mention, due, neonatal, respiratory, hemorrhage
target_16: open, unspecified, fracture, injury, loss, without, wound, consciousness, closed, mention, intracranial, degree, skull, body, hemorrhage
target_17: accident, injuring, vehicle, involving, motor, unspecified, causing, effects, accidental, therapeutic, use, adverse, poisoning, injury, collision
target_18: history, personal, unspecified, screening, malignant, examination, family, status, neoplasm, specified, suspected, vaccination, prophylactic, need, aftercare

# ENCODER CONFIGURATION
base_encoder: bionlp/bluebert_pubmed_mimic_uncased_L-12_H-768_A-12  # BlueBERT for clinical text (paper p.9)
use_custom_encoder: true                # Uses BlueBERT instead of default encoder
normalize_embeddings: false             # Whether to normalize embeddings

# KEYWORD EXTRACTION
topk: 40                               # Top-k labeling functions per class
min_df: 0.001                           # Document frequency threshold (paper p.8)
ngram_range: !!python/tuple             # Extract 1-3 grams as keywords
- 1
- 3

# LABEL MODEL CONFIGURATION
label_model: data_programming           # Using data programming
label_model_lr: 0.01                    # Learning rate for label model
label_model_n_epochs: 100               # Number of epochs for label model
use_noise_aware_loss: true              # Using noise-aware loss for weak labels

# DOWNSTREAM CLASSIFIER ARCHITECTURE
h_sizes:                                # Neural network architecture (paper p.11)
- 768                                   # Input size (BlueBERT embedding dimension)
- 256                                   # Hidden layer 1
- 64                                    # Hidden layer 2
- 19                                    # Output layer (19 classes for MIMIC)
activation: torch.nn.LeakyReLU()        # LeakyReLU activation (paper p.11)
criterion: torch.nn.BCEWithLogitsLoss(reduction='none')  # Binary loss for multilabel classification (paper p.11)

# DOWNSTREAM CLASSIFIER TRAINING
end_model_batch_size: 128               # Batch size for training (paper p.11)
end_model_epochs: 20                    # Maximum training epochs (paper p.11)
end_model_lr: 1e-3                      # Learning rate (paper p.11)
end_model_patience: 2                   # Early stopping patience (paper p.11)
end_model_weight_decay: 1e-4            # Weight decay for regularization

# SELF-TRAINING CONFIGURATION
self_train_batch_size: 8                # Batch size for self-training
self_train_lr: 1e-6                     # Learning rate for self-training
self_train_patience: 3                  # Early stopping patience for self-training
self_train_thresh: 1-2e-3               # Agreement threshold (1-0.002 = 0.998)
self_train_weight_decay: 1e-4           # Weight decay for self-training
q_update_interval: 50                   # Target distribution update frequency

# EVALUATION CONFIGURATION
average: samples                       # Type of averaging for metrics (paper footnote 4.)
n_bootstrap: 100                        # Bootstrap samples for confidence intervals

# INFRASTRUCTURE & LOGGING PARAMETERS
device: cuda                            # Hardware accelerator to use
n_jobs: 10                              # Number of parallel jobs
show_progress_bar: true                 # Display progress during training
log_path: ../logs/                      # Log file path
results_path: ../results/mimic/         # Path for results