name: Make Repository Public Scheduled

on:
  schedule:
    # Runs at 03:00 UTC on the 8th of May.
    # This corresponds to 10:00 PM Chicago Time (CDT, UTC-5) on May 7th.
    # Chicago Time (America/Chicago) is CDT (UTC-5) in May.
    # 10:00 PM CDT May 7th = 22:00 CDT May 7th = 03:00 UTC May 8th.
    - cron: '0 3 8 5 *'
  workflow_dispatch: # Allows manual triggering for testing

jobs:
  make_public:
    runs-on: ubuntu-latest
    # No specific GITHUB_TOKEN permissions needed at the job level for this,
    # as the critical step uses a PAT.
    # permissions: {} # You can even make this empty or remove the permissions block

    steps:
      - name: Get current year
        id: get_year
        run: echo "YEAR=$(date +'%Y')" >> $GITHUB_OUTPUT

      - name: Make repository public on specific date
        # This step only runs if it's the target year (2025)
        if: steps.get_year.outputs.YEAR == '2025'
        env:
          # This GH_TOKEN uses the PAT you stored as a secret.
          # The GitHub CLI (gh) will automatically use this token.
          GH_TOKEN: ${{ secrets.ADMIN_PAT }} # Ensure you have this secret configured
          REPO_NAME: ${{ github.repository }} # e.g., owner/repo-name
        run: |
          echo "Scheduled time: May 7th, 2025, 10 PM Chicago Time (03:00 UTC May 8th, 2025)."
          echo "Current UTC date and time: $(date -u)"
          echo "Attempting to make repository '$REPO_NAME' public using PAT..."
          
          gh repo edit $REPO_NAME --visibility public --accept-visibility-change-consequences
          
          echo "Repository '$REPO_NAME' visibility has been set to public."
          echo "SUCCESS! This workflow has completed its one-time task."
          echo "Consider disabling or deleting this workflow now to prevent future runs on May 8th of other years."

      - name: Log if not the target year
        if: steps.get_year.outputs.YEAR != '2025'
        run: |
          echo "Skipping repository visibility change: Not the target year 2025."
          echo "Current year: ${{ steps.get_year.outputs.YEAR }}."
          echo "This workflow is intended to run the 'make public' step only on May 8th, 2025 (UTC)."
